# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    #data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:testdb
    username: saß
    password: password
  application:
    name: service-edu
profiles:
  active: dev

server:
  port: 8001
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mapper-locations: classpath:com.kenkoku.service/*/mapper/*.xml
#global-config:
#  db-config:
#    logic-delete-value: 1
#    logic-not-delete-value: 0


# Logger Config
#logging:
#  level:
#    com.baomidou.my
#    batisplus.samples.wrapper: debug